# Spring Boot application configuration

# Server configuration
server:
  port: 8081

# Database configuration
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.core.serializer.JsonSerializer
  application:
    name: "cliente-service"
  datasource:
    url: jdbc:mysql://localhost:3306/lavanderia_inventario
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Logging configuration
logging:
  level:
    root: INFO
    com.example: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# Custom application properties
custom:
  app:
    name: Lavanderia Maione
    version: 1.0
    description: Gestionale della lavanderia Maione
